spring:
  application:
    name: task-manager
#  profiles:
#    active: dev
logging:
  level:
    org.springframework: info
  #  jpa:
  #    generate-ddl: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 6
#  mongodb:
#    username: admin
#    password: admin
#    database: payments
#    authentication-database: admin
#    # host: localhost
#    # port: 27017
  messages:
    basename: exceptions

